### ISSUE TITLE
Bundle does not support "version"

### ISSUE THREAD

**Issue by royragsdale** [picoCTF/picoCTF-shell-manager#80]
The [documentation](https://github.com/picoCTF/picoCTF-platform/wiki/Bundle.json) states that a bundle.json can have a `version` field.

However the [bundle schema](https://github.com/picoCTF/picoCTF-web/blob/5c4e87c1786e775d38c722460b621453fc2fc9d5/api/problem.py#L77) does not include this field.

A bundle can be successfully installed on a shell server that includes the version. However when picoCTF-web attempts to load a deployment it results in an exception `voluptuous.MultipleInvalid: extra keys not allowed @ data['version']`

Possible solutions: 
1. Explicitly add the version field to the schema
2. Change the schema checking to be more permissive and allow extra keys

Additional considerations:
There may not be a great way to do this while keeping shell_manager and picoCTF-web loosely coupled, but if we are going to strictly specify valid schemas, in picoCTF-web, related to the published deployment json, it would be nice if the same strict enforcement was applied within shell_manager.

Full Exception traceback.

```
Traceback (most recent call last):
  File "/picoCTF-web/api/common.py", line 196, in validate
    schema(data)
  File "/usr/local/lib/python3.4/dist-packages/voluptuous.py", line 337, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.4/dist-packages/voluptuous.py", line 635, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.4/dist-packages/voluptuous.py", line 471, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: extra keys not allowed @ data['version']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/picoCTF-web/api/annotations.py", line 57, in wrapper
    web_result = f(*args, **kwds)
  File "/picoCTF-web/api/annotations.py", line 132, in wrapper
    return f(*args, **kwds)
  File "/picoCTF-web/api/routes/admin.py", line 132, in load_problems_from_shell_server
    number = api.shell_servers.load_problems_from_server(sid)
  File "/picoCTF-web/api/shell_servers.py", line 221, in load_problems_from_server
    api.problem.load_published(data)
  File "/picoCTF-web/api/problem.py", line 880, in load_published
    insert_bundle(bundle)
  File "/picoCTF-web/api/problem.py", line 849, in insert_bundle
    validate(bundle_schema, bundle)
  File "/picoCTF-web/api/common.py", line 198, in validate
    raise APIException(0, None, error.msg)
api.common.APIException: (0, None, 'extra keys not allowed')
```

**Comment by tim-becker** [comment]
Thanks for writing this up. I agree that we should enforce the same schemas on both the shell and web side of things.

For now, I'll go and add `version` to the web schema, but we should leave this issue open until the larger issue is addressed appropriately.
